title: Github Lab Test Jekyll Page
author: stephenhage
email: stephenhage2017@u.northwestern.edu
description: > # this means to ignore newlines until "baseurl:"
  Learning more about github pages so I can get a good site up and running
# social links
linkedin_username: stephenhage
github_username:  stephenhage

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
